# Generated by Django 6.0 on 2026-08-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('sub_heading', models.TextField()),
                ('button_text', models.CharField(max_length=100)),
                ('button_link', models.CharField(default='#', max_length=200)),
                ('image', models.ImageField(upload_to='hero/')),
            ],
        ),
    ]
