# Generated by Django 6.0 on 2026-09-01 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='heading_green',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
