# Generated by Django 6.1 on 2026-09-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='button_text',
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_text',
            field=models.CharField(default='Free delivery on orders above Rs. 2,500', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
    ]
