# Generated by Django 6.0 on 2026-09-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='formula_image',
            field=models.ImageField(blank=True, help_text='Custom middle image for Natural Formula section (optional)', null=True, upload_to='formula/'),
        ),
    ]
