# Generated by Django 6.0 on 2026-09-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_formula_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormulaSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_title', models.CharField(default='NATURAL FORMULA', max_length=200)),
                ('title', models.CharField(default='Powered By Nature', max_length=200)),
                ('description', models.TextField(default='Carefully selected natural ingredients come together to create a nourishing hair-care formula.')),
                ('center_image', models.ImageField(help_text='Upload middle image for Natural Formula section', upload_to='formula/')),
            ],
        ),
    ]
