# Generated by Django 6.1 on 2026-09-15 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_order_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='badge',
            field=models.CharField(blank=True, default='Starter Pack', help_text='e.g. Starter Pack, Most Popular, Best Value', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Highlight card with featured border & badge'),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(default='50ml', help_text='e.g. 50ml, 80ml, 120ml', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='subtitle',
            field=models.CharField(blank=True, help_text='e.g. 50ml Trial & Travel Edition', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.PositiveIntegerField(default=0, help_text='Discount percentage e.g. 25, 30'),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Previous / Old Price', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Current / New Price', max_digits=10),
        ),
    ]
