# Generated by Django 6.1 on 2026-10-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_product_badge_product_is_featured_product_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Customer full name e.g. Sarah Ahmed', max_length=150)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=5, help_text='Rating out of 5 stars')),
                ('comment', models.TextField(help_text='Customer review feedback text')),
                ('verified_badge', models.CharField(default='Verified Customer', help_text='e.g. Verified Customer, Verified Buyer', max_length=100)),
                ('city', models.CharField(blank=True, help_text='Optional city e.g. Lahore, Karachi, Islamabad', max_length=100, null=True)),
                ('image', models.ImageField(blank=True, help_text='Optional customer avatar/photo', null=True, upload_to='reviews/')),
                ('is_approved', models.BooleanField(default=True, help_text='Check to display on the website')),
                ('is_featured', models.BooleanField(default=False, help_text='Pin to the front')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (0 shows first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewSectionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default='Customer Love', help_text='Small top badge text', max_length=100)),
                ('heading', models.CharField(default='Loved By Hair', help_text='Main heading before highlight', max_length=200)),
                ('heading_green', models.CharField(default='Care Lovers', help_text='Highlighted green part of heading', max_length=200)),
                ('sub_heading', models.TextField(default='See what our customers have to say about their hair-care experience.', help_text='Subtitle under heading')),
                ('rating_score', models.DecimalField(decimal_places=1, default=4.9, help_text='Overall displayed rating (e.g. 4.9)', max_digits=3)),
                ('total_reviews_text', models.CharField(default='Based on 128 reviews', help_text='e.g. Based on 128 reviews, 500+ Happy Customers', max_length=100)),
                ('verified_label', models.CharField(default='Verified customer reviews', help_text='Verified label text', max_length=100)),
            ],
            options={
                'verbose_name': 'Reviews Section Setting',
                'verbose_name_plural': 'Reviews Section Settings',
            },
        ),
    ]
