# Generated by Django 6.1 on 2026-10-02 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_review_reviewsectionsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='formula_image',
        ),
    ]
