# Generated by Django 6.0 on 2026-10-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_product_formula_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hero',
            options={'verbose_name': 'Hero Section', 'verbose_name_plural': 'Hero Section'},
        ),
        migrations.AddField(
            model_name='hero',
            name='badge_text',
            field=models.CharField(default='100% Natural Hair Care', help_text="Small badge shown above the heading e.g. '100% Natural Hair Care'", max_length=100),
        ),
        migrations.AddField(
            model_name='hero',
            name='floating_card_label',
            field=models.CharField(default='Natural Care', help_text="Small label on floating card e.g. 'Natural Care'", max_length=100),
        ),
        migrations.AddField(
            model_name='hero',
            name='floating_card_value',
            field=models.CharField(default='For Healthy Hair', help_text="Bold text on floating card e.g. 'For Healthy Hair'", max_length=100),
        ),
        migrations.AddField(
            model_name='hero',
            name='rating_card_text',
            field=models.CharField(default='Loved by customers', help_text="Text shown below stars on rating card e.g. 'Loved by customers'", max_length=100),
        ),
        migrations.AddField(
            model_name='hero',
            name='trust_point_1',
            field=models.CharField(default='Natural', help_text='First trust point text', max_length=100),
        ),
        migrations.AddField(
            model_name='hero',
            name='trust_point_2',
            field=models.CharField(default='Chemical Free', help_text='Second trust point text', max_length=100),
        ),
        migrations.AddField(
            model_name='hero',
            name='trust_point_3',
            field=models.CharField(default='Cruelty Free', help_text='Third trust point text', max_length=100),
        ),
        migrations.AlterField(
            model_name='hero',
            name='button_link',
            field=models.CharField(default='#shop', max_length=200),
        ),
        migrations.AlterField(
            model_name='hero',
            name='button_text',
            field=models.CharField(default='Shop Now', max_length=100),
        ),
        migrations.AlterField(
            model_name='hero',
            name='heading',
            field=models.CharField(default='Revive Your Hair', max_length=200),
        ),
        migrations.AlterField(
            model_name='hero',
            name='heading_green',
            field=models.CharField(default='Naturally', max_length=200),
        ),
        migrations.AlterField(
            model_name='hero',
            name='sub_heading',
            field=models.TextField(default='Experience the power of nature with our premium hair growth oil — crafted to nourish, strengthen, and revive your hair from root to tip.'),
        ),
    ]
