# Generated by Django 6.0 on 2026-10-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_hero_options_hero_badge_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Blog post title', max_length=300)),
                ('slug', models.SlugField(help_text='URL slug (auto-filled from title)', max_length=300, unique=True)),
                ('excerpt', models.TextField(help_text='Short summary shown on card (2-3 lines)', max_length=500)),
                ('content', models.TextField(help_text='Full blog article content (HTML supported)')),
                ('image', models.ImageField(help_text='Featured image for the blog post', upload_to='blog/')),
                ('category', models.CharField(choices=[('hair_care', 'Hair Care'), ('tips', 'Tips & Tricks'), ('ingredients', 'Ingredients'), ('lifestyle', 'Lifestyle'), ('guides', 'Guides')], default='hair_care', max_length=50)),
                ('author', models.CharField(default='HairGlow Team', max_length=150)),
                ('read_time', models.PositiveIntegerField(default=5, help_text='Estimated read time in minutes')),
                ('is_published', models.BooleanField(default=True, help_text='Show on website?')),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage journal section?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-created_at'],
            },
        ),
    ]
